# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Tech
    url: tags/tech/
    weight: 22
  - name: Topics
    url: tags/
    weight: 30
  # - name: Uses
  #   url: uses/
  #   weight: 30
